test_0 (__main__.lab2a)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for file creation: ./lab2a.py ... ok
test_1 (__main__.lab2a)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for errors running: ./lab2a.py ... /usr/lib/python3.10/subprocess.py:767: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
  _cleanup()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_2 (__main__.lab2a)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct shebang line: ./lab2a.py ... ok
test_3 (__main__.lab2a)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct output: ./lab2a.py ... ok
test_0 (__main__.lab2b)
[Lab 2] - [Investigation 1] - [Part 1] - using input() function - Test for file creation: ./lab2b.py ... ok
test_1 (__main__.lab2b)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test for errors with sending input "Jon" "20": ./lab2b.py ... ok
test_2 (__main__.lab2b)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test for correct shebang line: ./lab2b.py ... ok
test_3 (__main__.lab2b)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test output with sending input "Jon" "20": ./lab2b.py ... ok
test_4 (__main__.lab2b)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test output with sending input "Jen" "25": ./lab2b.py ... ok
test_0 (__main__.lab2c)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test for file creation: ./lab2c.py ... ok
test_1 (__main__.lab2c)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test for errors with 2 args: ./lab2c.py Jon 20 ... ok
test_2 (__main__.lab2c)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test for correct shebang line: ./lab2c.py ... ok
test_3 (__main__.lab2c)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test output for: ./lab2c.py Jon 20 ... FAIL

======================================================================
FAIL: test_3 (__main__.lab2c)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test output for: ./lab2c.py Jon 20
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/twangmo12/OPS445-ZAA/lab2/./CheckLab2.py", line 157, in test_3
    self.assertEqual(stdout, expected_output, msg=error_output)
AssertionError: b'Hello Jon, you are 20 years old.\n' != b'Hi Jon, you are 20 years old.\n' : output is not correct (HINT: must use the sys.argv list, do not forget to import sys)

----------------------------------------------------------------------
Ran 13 tests in 0.068s

FAILED (failures=1)
OPS445 Lab Report - System Information for running ./CheckLab2.py
=================================================================
    User login name: twangmo12
    Git Email: twangmo12@myseneca.ca
    Linux system name: Tandin-Wangmo
    Python executable: /usr/bin/python3
    Python version:  3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
    OS Platform: linux
    Working Directory: /home/twangmo12/OPS445-ZAA/lab2
    Start at: Wed Sep 25 12:46:49 2024
=================================================================
